#Obtener todos los doctores
GET http://localhost:8080/api/v1/doctores/

#Añadir un doctor
POST http://localhost:8080/api/v1/doctores/
Content-Type: application/json
Accept: application/json
Content:

{
  "username": "Carlos",
  "password": "carlospro123",
  "especialidad": "Neurologia",
  "persona": {
    "nombre": "Charles Deniel",
    "apellido": "Nina Reynaga",
    "numeroTel": "67867868",
    "direccion": "Av. America #123"
  }
}

# Aqui necesitamos ID del doctor 4 e igualmente la informacion de PERSONA se cambia junto al doctor
PUT http://localhost:8080/api/v1/doctores/4
Content-Type: application/json
Accept: application/json
Content:

{
  "username": "EditadoJose",
  "password": "editado",
  "especialidad": "Pediatria",
  "persona": {
    "nombre": "Jose Jose",
    "apellido": "Perez joka",
    "numeroTel": "768678",
    "direccion": "Av. America #1142"
  }
}

# Eliminar un doctor
DELETE http://localhost:8080/api/v1/doctores/4

# Esto saldra si un doctor es eliminado y se genera una cita agendada asi que nos corresponde
# eliminar la cita agendada antes del doctor

{
    "code": "Result-1000",
    "result": null,
    "message": "could not execute statement [ERROR: update or delete on table \"doctor\"
    violates foreign key constraint \"cita_agendada_doctor\" on table \"cita_agendada\"\n
    Detail: Key (id_doctor)=(3) is still referenced from table \"cita_agendada\".] [delete
    from doctor where id_doctor=?]; SQL [delete from doctor where id_doctor=?]; constraint
    [cita_agendada_doctor]"
}
